### ISSUE TITLE
DDlog does not support overflow of signed constants

### ISSUE THREAD

**Issue by mbudiu-vmw** [vmware/differential-datalog#294] opened 2019-07-10 01:15 UTC
This program crashes at Rust compilation time:
```
output relation RR(_n:signed<32>)
RR(- (2147483648)).
```

I think that this program should be legal.

**Comment by ryzhyk** [comment] 2019-07-10 07:28
This should be easy to fix.  The problem is that we already use wrapping versions of all arithmetic operations, but not unary minus.

**Comment by ryzhyk** [comment] 2019-07-11 16:17
Fixed in #296

**Closed by ryzhyk** 2019-07-11 16:17 UTC
Labels: bug
