### ISSUE TITLE
Non-deterministic crash in TcpChannel test

### ISSUE THREAD

**Issue by ryzhyk** [vmware/differential-datalog#427] opened 2019-10-14 05:30 UTC
The following error comes up non-deterministically after running the `cargo test` command several times (on the current master)

```
~/projects/differential-datalog/rust/template$ RUST_BACKTRACE=1 cargo test --all
    Finished dev [unoptimized + debuginfo] target(s) in 0.07s
     Running target/debug/deps/cmd_parser-4399302d4771aa1f

running 7 tests
test parse::test_bool ... ok
test parse::test_array ... ok
test parse::test_string ... ok
test parse::test_int ... ok
test parse::test_tuple ... ok
test parse::test_command ... ok
test parse::test_struct ... ok

test result: ok. 7 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/datalog_example_ddlog-b5ce151223437306

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/datalog_example_cli-c68425d7fb51656b

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/interact_dump_error-36c35471804938f7

running 1 test

running 1 test
test interact_dump_error ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/interact_exit-785b5c8ed6c35f37

running 1 test

running 1 test
test interact_exit ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/ddlog_ovsdb_adapter-07d73bc91eb6d817

running 1 test
test test::test_parser ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/differential_datalog-21148c7d46ac7d5c

running 33 tests
test int::test_fromrecord ... ok
test record::tests::dump_record ... ok
test test::test_join_multi ... ok
test test::test_antijoin_multi ... ok
test test::test_join_1 ... ok
test test::test_multiple_stops ... ok
test test::test_antijoin_1 ... ok
test test::test_one_relation_1 ... ok
test test::test_recursion_1 ... ok
test test::test_semijoin_1 ... ok
test test::test_recursion_multi ... ok
test test::test_semijoin_multi ... ok
test test::test_two_relations_multi ... ok
test test_record::test_array ... ok
test test::test_two_relations_1 ... ok
test test_record::test_biguint ... ok
test test_record::test_bigint ... ok
test test_record::test_bool ... ok
test test_record::test_enum ... ok
test test_record::test_map ... ok
test test_record::test_set ... ok
test test_record::test_string ... ok
test test_record::test_struct ... ok
test test_record::test_u128 ... ok
test test_record::test_tuple ... ok
test test_record::test_u16 ... ok
test test_record::test_u64 ... ok
test test_record::test_u32 ... ok
test test_record::test_u8 ... ok
test test_record::test_vec ... ok
test uint::test_fromrecord ... ok
test test::test_map_1 ... ok
test test::test_map_multi ... ok

test result: ok. 33 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/observe-e69308edabb49497

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/tcp_channel-47e8e821780db0fb

running 4 tests
test sender::tests::connect::f ... ok
test receiver::tests::never_accepted::f ... ok
test receiver::tests::accept::f ... ok
test sender::tests::transmit_updates_no_consumer::f ... ok

test result: ok. 4 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests cmd_parser

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests ddlog_ovsdb_adapter

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests differential_datalog

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests observe

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests tcp_channel

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests datalog_example_ddlog

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

lryzhyk@cocoon:~/projects/differential-datalog/rust/template$ RUST_BACKTRACE=1 cargo test --all
    Finished dev [unoptimized + debuginfo] target(s) in 0.06s
     Running target/debug/deps/cmd_parser-4399302d4771aa1f

running 7 tests
test parse::test_bool ... ok
test parse::test_array ... ok
test parse::test_int ... ok
test parse::test_string ... ok
test parse::test_command ... ok
test parse::test_tuple ... ok
test parse::test_struct ... ok

test result: ok. 7 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/datalog_example_ddlog-b5ce151223437306

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/datalog_example_cli-c68425d7fb51656b

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/interact_dump_error-36c35471804938f7

running 1 test

running 1 test
test interact_dump_error ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/interact_exit-785b5c8ed6c35f37

running 1 test

running 1 test
test interact_exit ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/ddlog_ovsdb_adapter-07d73bc91eb6d817

running 1 test
test test::test_parser ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/differential_datalog-21148c7d46ac7d5c

running 33 tests
test int::test_fromrecord ... ok
test record::tests::dump_record ... ok
test test::test_join_multi ... ok
test test::test_join_1 ... ok
test test::test_antijoin_1 ... ok
test test::test_multiple_stops ... ok
test test::test_antijoin_multi ... ok
test test::test_one_relation_1 ... ok
test test::test_recursion_1 ... ok
test test::test_semijoin_1 ... ok
test test::test_recursion_multi ... ok
test test::test_semijoin_multi ... ok
test test::test_two_relations_1 ... ok
test test_record::test_array ... ok
test test_record::test_bigint ... ok
test test_record::test_biguint ... ok
test test_record::test_bool ... ok
test test_record::test_enum ... ok
test test_record::test_map ... ok
test test_record::test_set ... ok
test test_record::test_string ... ok
test test_record::test_struct ... ok
test test_record::test_tuple ... ok
test test_record::test_u128 ... ok
test test_record::test_u16 ... ok
test test_record::test_u32 ... ok
test test_record::test_u64 ... ok
test test_record::test_u8 ... ok
test test_record::test_vec ... ok
test uint::test_fromrecord ... ok
test test::test_two_relations_multi ... ok
test test::test_map_1 ... ok
test test::test_map_multi ... ok

test result: ok. 33 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/observe-e69308edabb49497

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/tcp_channel-47e8e821780db0fb

running 4 tests
test receiver::tests::accept::f ... ok
test receiver::tests::never_accepted::f ... ok
test sender::tests::connect::f ... ok
[2019-10-14T05:27:22Z ERROR tcp_channel::receiver] failed to deserialize message: io error: Bad file descriptor (os error 9)
[2019-10-14T05:27:22Z ERROR tcp_channel::receiver] failed to deserialize message: io error: Bad file descriptor (os error 9)
[2019-10-14T05:27:22Z ERROR tcp_channel::receiver] failed to deserialize message: io error: Bad file descriptor (os error 9)
[2019-10-14T05:27:22Z ERROR tcp_channel::receiver] failed to deserialize message: io error: Bad file descriptor (os error 9)
[2019-10-14T05:27:22Z ERROR tcp_channel::receiver] failed to deserialize message: io error: Bad file descriptor (os error 9)
test sender::tests::transmit_updates_no_consumer::f ... FAILED

failures:

---- sender::tests::transmit_updates_no_consumer::f stdout ----
thread 'sender::tests::transmit_updates_no_consumer::f' panicked at 'called `Result::unwrap()` on an `Err` value: "io error: Broken pipe (os error 32)"', src/libcore/result.rs:1084:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:47
   3: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:36
   4: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:200
   5: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   6: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:477
   7: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   8: rust_begin_unwind
             at src/libstd/panicking.rs:311
   9: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  10: core::result::unwrap_failed
             at src/libcore/result.rs:1084
  11: core::result::Result<T,E>::unwrap
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libcore/result.rs:852
  12: tcp_channel::sender::tests::transmit_updates_no_consumer
             at tcp_channel/sender.rs:87
  13: tcp_channel::sender::tests::transmit_updates_no_consumer::f
             at tcp_channel/sender.rs:79
  14: tcp_channel::sender::tests::transmit_updates_no_consumer::f::{{closure}}
             at tcp_channel/sender.rs:79
  15: core::ops::function::FnOnce::call_once
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libcore/ops/function.rs:235
  16: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/liballoc/boxed.rs:787
  17: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  18: std::panicking::try
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/panicking.rs:275
  19: std::panic::catch_unwind
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libstd/panic.rs:394
  20: test::run_test::run_test_inner::{{closure}}
             at src/libtest/lib.rs:1408
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[2019-10-14T05:27:22Z ERROR tcp_channel::receiver] failed to close TcpReceiver file descriptor: Bad file descriptor (os error 9)


failures:
    sender::tests::transmit_updates_no_consumer::f

test result: FAILED. 3 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '-p tcp_channel --lib'
```

**Comment by d-e-s-o** [comment] 2019-10-14 15:21
I have seen that too, but so far have not been able to make sense of the problem. I've only ever seen it occur when other tests are running alongside and wanted to make sure it's not specific to my system (which I guess is now confirmed). I managed to get an `strace` but that didn't make things clear either. I'll continue looking into it.

**Comment by d-e-s-o** [comment] 2019-10-14 15:22
If that is making the CI pipeline flaky we can disable the test for now.

**Comment by ryzhyk** [comment] 2019-10-14 15:26
I haven't seen the CI fail because of this yet.

**Comment by d-e-s-o** [comment] 2019-10-14 23:42
Okay, here is one hypothesis: I see no way that a socket could be closed incorrectly in this test when run in isolation. The test seems to agree. So, that leaves us with constellations involving multiple threads.

Here is the implementation of `Drop` for `FileDesc`, which is the lowest level object used for implementing `TcpListener` & `TcpStream`:
```
impl Drop for FileDesc {
    fn drop(&mut self) {
        // Note that errors are ignored when closing a file descriptor. The
        // reason for this is that if an error occurs we don't actually know if
        // the file descriptor was closed or not, and if we retried (for
        // something like EINTR), we might close another valid file descriptor
        // opened after we closed ours.
        let _ = unsafe { libc::close(self.fd) };
    }
}
```
I believe we could be hitting such an issue described in the comment in our setup. In particular, the individual tests are running as threads in the same address space from what I understand, meaning they share the file descriptor namespace.
So what I suppose could happen is the following:
- `TcpReceiver` is dropped which closes `Fd` which in turn calls `close(2)` on the file descriptor we have
- now that the file descriptor is closed it can be reused; that so happens for the next test running
- because of the earlier close we unblock, say, `accept(2)` or `recv(2)` (depending on whatever state we are in) in the "accepter" thread
  - we eventually exit this thread, dropping the `TcpListener` / `TcpStream` in the process; now these objects still believe that their file descriptor is valid and try to close it again, which will now close the new file descriptor
  - Boom.

**Comment by d-e-s-o** [comment] 2019-10-15 23:15
I can confirm that the above is the issue and I do have a fix for it. Unfortunately it's not pretty and I am struggling to make it so.

**Closed** 2019-10-18 16:44 UTC
