### ISSUE TITLE
How to add trait bound on generic type?

### ISSUE THREAD

**Issue by qishen** [vmware/differential-datalog#1017] opened 2021-07-04 01:56 UTC
The compiler complains that `N` needs to be restricted by trait bound `Clone` when I'm calling the Rust APIs. Is there any way I can add the trait bound on the generic type in ddlog program or I have to change it to an extern type in the native Rust constructor with whatever trait bounds I want to add?
```
typedef List<'N> = List { node: 'N, nxt: ListNxt<'N> } | EMPTY
typedef ListNxt<'N> = ListNxt { nxt: Ref<List<'N>> }
```

Below is the generated code from ddlog program that does not enforce `Clone` on the generic type `N`.
```Rust
#[derive(Eq, Ord, Clone, Hash, PartialEq, PartialOrd, IntoRecord, Mutator, Serialize, Deserialize, FromRecord)]
#[ddlog(rename = "List")]
pub enum List<N> {
    #[ddlog(rename = "List")]
    List {
        node: N,
        nxt: ListNxt<N>
    },
    #[ddlog(rename = "EMPTY")]
    EMPTY
}
impl <N: ::ddlog_rt::Val> abomonation::Abomonation for List<N>{}
```

**Comment by ryzhyk** [comment] 2021-07-04 06:14
I believe this is a bug in our procedural macros that auto-derive `IntoRecord` and `Mutator` traits.

```
error[E0277]: the trait bound `N: Clone` is not satisfied
   --> types/list.rs:128:9
    |
128 |     pub nxt: ddlog_std::Ref<List<N>>
    |         ^^^
    |         |
    |         expected an implementor of trait `Clone`
    |         help: consider borrowing here: `&nxt`
    |
    = note: required because of the requirements on the impl of `Clone` for `List<N>`
    = note: required because of the requirements on the impl of `IntoRecord` for `ddlog_std::Ref<List<N>>`
    = note: required by `into_record`

error[E0277]: the trait bound `N: Clone` is not satisfied
   --> types/list.rs:125:67
    |
125 | #[derive(Eq, Ord, Clone, Hash, PartialEq, PartialOrd, IntoRecord, Mutator, Default, Serialize, Deserialize, FromRecord)]
    |                                                                   ^^^^^^^ the trait `Clone` is not implemented for `N`
    |
    = note: required because of the requirements on the impl of `Clone` for `List<N>`
    = note: required because of the requirements on the impl of `Mutator<ddlog_std::Ref<List<N>>>` for `Record`
    = note: required for the cast to the object type `dyn Mutator<ddlog_std::Ref<List<N>>>`
    = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider further restricting type parameter `N`
    |
125 | #[derive(Eq, Ord, Clone, Hash, PartialEq, PartialOrd, IntoRecord, Mutator, N: Clone, Default, Serialize, Deserialize, FromRecord)]
    |                                                                          ^^^^^^^^^^

```

I think we need to add more trait bounds on generic arguments, e.g., [here](https://github.com/ddlog-dev/differential-datalog/blob/14c398fa89568a6632e492e55087a365d6a7d01b/rust/template/ddlog_derive/src/into_record.rs#L20)

cc: @Kixiron

**Comment by ryzhyk** [comment] 2021-07-04 16:50
The root of the problem is that IntoRecord takes ownership of the input. This is not always a good idea, as in the case of Ref<>, where we need to clone the inner value to get an owned copy of it. One workaround would be to additionally require that every ddlog type T satisfies both T: IntoRecord and &T: IntoRecord.

**Comment by qishen** [comment] 2021-07-05 21:37
Thanks for the clarification and quick fix! By the way, do you guys want a linked list type to be part of your std library in `ddlog_std.dl`? It's not memory-efficient because of `Ref<T>` but could be useful in some use cases. For example, flatten out a list and map each element in the list to a separate record while it's hard to do if the type is `Vec<T>`

**Comment by Kixiron** [comment] 2021-07-05 22:12
I'm not sure what you mean, how would a linked list be better in that situation? Continuous vectors are better than linked lists in 99% of situations, this sounds like something addressed by better iteration or more iterator adaptors instead of a new type

**Comment by qishen** [comment] 2021-07-05 22:50
@Kixiron I wonder how would you write a rule in ddlog to map every element in one vector from the `Vector` relation into multiple records in the `Record` relation? It would be easier to do it in the linked list I defined above even though I may end up using too many `deref()` to iterate the linked list.

```
typedef Vector = Vector { inner: Vec<usize> }
typedef Record = Record { inner: usize }

input relation Vector [Vector]
output relation Record [Record]

Record[?] :- Vector[Vector { vector }].
```

**Comment by Kixiron** [comment] 2021-07-05 23:18
This should work
```prolog
Record[Record { inner }] :- Vector[Vector { vector }], var inner = FlatMap(vector).
```

**Comment by ryzhyk** [comment] 2021-07-06 04:32
Yep, I don't think we need a list type in this example, but it would still be nice to have it as a library.

**Comment by Kixiron** [comment] 2021-07-06 04:52
Eh, with how little the linked list type in the rust stdlib is used I don't think it's worth the upkeep cost or the performance impact if it's ever actually used

**Closed** 2021-07-06 17:26 UTC
Labels: bug
